---
imports:
  - path: notebook_instance.jinja


resources:
  - name: vwt-d-gew1-{{cookiecutter.project_id}}-notebook
    type: notebook_instance.jinja
    properties:
      service-account: data-science
