---
timeout: 1200s
steps:
  # Deploy data catalog
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone --branch=${BRANCH_NAME} https://github.com/vwt-digital/dcat-deploy.git
        dcat-deploy/deploy_dcat_gcp.sh config/${PROJECT_ID}/data_catalog.json ${PROJECT_ID} ${BRANCH_NAME}

  # Get notebook-deployment repo
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - '--branch=${BRANCH_NAME}'
      - 'https://github.com/vwt-digital/notebook-deployment.git'

  # Copy
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp config/${PROJECT_ID}/config.yaml notebook-deployment/notebook-vm/


  # Deploy vm with notebook
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - sh deploy.sh ${PROJECT_ID} ${PROJECT_ID}-notebook-vm
    dir: 'notebook-deployment/notebook-vm'

  # Copy autoshutdown to the vm and start the service
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp notebook-deployment/notebook-vm/ashutdown \
          ${PROJECT_ID}-notebook-vm:/usr/local/bin/ \
          --zone europe-west1-b
        gcloud compute scp notebook-deployment/notebook-vm/ashutdown.service \
          ${PROJECT_ID}-notebook-vm:/lib/systemd/system/ \
          --zone europe-west1-b
        gcloud compute ssh ${PROJECT_ID}-notebook-vm \
          --command="systemctl --no-reload --now enable /lib/systemd/system/ashutdown.service" \
          --zone europe-west1-b
