---
timeout: 1200s
steps:
  # Deploy data catalog
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone --branch=${BRANCH_NAME} https://github.com/vwt-digital/dcat-deploy.git
        dcat-deploy/deploy_dcat_gcp.sh config/${PROJECT_ID}/data_catalog.json ${PROJECT_ID} ${BRANCH_NAME}
